use std::str::FromStr;

#[derive(Clone, Debug)]
pub enum Operator {
    Acall,
    Add,
    Addc,
    Ajmp,
    Anl,
    Call,
    Cjne,
    Clr,
    Cpl,
    Da,
    Dec,
    Div,
    Djnz,
    Inc,
    Jb,
    Jbc,
    Jc,
    Jmp,
    Jnb,
    Jnc,
    Jnz,
    Jz,
    Lcall,
    Ljmp,
    Mov,
    Movc,
    Movx,
    Mul,
    Nop,
    Orl,
    Pop,
    Push,
    Ret,
    Reti,
    Rl,
    Rlc,
    Rr,
    Rrc,
    Setb,
    Sjmp,
    Subb,
    Swap,
    Xch,
    Xchd,
    Xrl
}

impl FromStr for Operator {
    type Err = ();

    fn from_str(s: &str) -> Result<Operator, ()> {
        match s.to_lowercase().as_ref() {
            "acall" => Ok(Operator::Acall),
            "add" => Ok(Operator::Add),
            "addc" => Ok(Operator::Addc),
            "ajmp" => Ok(Operator::Ajmp),
            "anl" => Ok(Operator::Anl),
            "call" => Ok(Operator::Call),
            "cjne" => Ok(Operator::Cjne),
            "clr" => Ok(Operator::Clr),
            "cpl" => Ok(Operator::Cpl),
            "da," => Ok(Operator::Da),
            "dec" => Ok(Operator::Dec),
            "div" => Ok(Operator::Div),
            "djnz" => Ok(Operator::Djnz),
            "inc" => Ok(Operator::Inc),
            "jb," => Ok(Operator::Jb),
            "jbc" => Ok(Operator::Jbc),
            "jc," => Ok(Operator::Jc),
            "jmp" => Ok(Operator::Jmp),
            "jnb" => Ok(Operator::Jnb),
            "jnc" => Ok(Operator::Jnc),
            "jnz" => Ok(Operator::Jnz),
            "jz," => Ok(Operator::Jz),
            "lcall" => Ok(Operator::Lcall),
            "ljmp" => Ok(Operator::Ljmp),
            "mov" => Ok(Operator::Mov),
            "movc" => Ok(Operator::Movc),
            "movx" => Ok(Operator::Movx),
            "mul" => Ok(Operator::Mul),
            "nop" => Ok(Operator::Nop),
            "orl" => Ok(Operator::Orl),
            "pop" => Ok(Operator::Pop),
            "push" => Ok(Operator::Push),
            "ret" => Ok(Operator::Ret),
            "reti" => Ok(Operator::Reti),
            "rl," => Ok(Operator::Rl),
            "rlc" => Ok(Operator::Rlc),
            "rr," => Ok(Operator::Rr),
            "rrc" => Ok(Operator::Rrc),
            "setb" => Ok(Operator::Setb),
            "sjmp" => Ok(Operator::Sjmp),
            "subb" => Ok(Operator::Subb),
            "swap" => Ok(Operator::Swap),
            "xch" => Ok(Operator::Xch),
            "xchd" => Ok(Operator::Xchd),
            "xrl" => Ok(Operator::Xrl),
            _ => Err(())
        }
    }
}

#[derive(Clone, Debug)]
pub enum Register {
    R0,
    R1,
    R2,
    R3,
    R4,
    R5,
    R6,
    R7,
    PC,
    SP,
    DPTR
    // TODO
}

